name: shellcheck

on:
  pull_request:
    branches: 
      - 'dev'
    paths:
      - '*.sh'

jobs:
  shellcheck_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Shellcheck Action
      uses: fearphage/shellcheck-action@1.0.0
